#!/usr/bin/env python3
import argparse

from argo_scg.sensu import SensuCtl


def main():
    parser = argparse.ArgumentParser("Get event data")
    parser.add_argument(
        "--namespace", dest="namespace", default="default", help="namespace",
        type=str
    )
    args = parser.parse_args()

    sensuctl = SensuCtl(namespace=args.namespace)

    lines = sensuctl.get_events()

    for i in range(len(lines)):
        print(lines[i])
        if i > 1:
            print("\n")


main()
